/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Fork headless export: writes a simple Markdown triage summary to triage.md.
// READ-ONLY: does not modify the program. Output dir is script arg[0] (default ".").
//@category Fork.Headless

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.nio.charset.StandardCharsets;
import java.time.Instant;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.DataIterator;
import ghidra.program.model.mem.MemoryBlock;
import ghidra.program.model.symbol.SymbolIterator;

public class ForkTriageReport extends GhidraScript {

	@Override
	public void run() throws Exception {
		if (currentProgram == null) {
			printerr("ForkTriageReport: no current program; nothing to report.");
			return;
		}

		String name = currentProgram.getName();
		String languageId = currentProgram.getLanguage().getLanguageID().getIdAsString();
		String compilerSpec = currentProgram.getCompilerSpec().getCompilerSpecID().getIdAsString();
		String imageBase = (currentProgram.getImageBase() != null)
				? currentProgram.getImageBase().toString() : "(unknown)";

		MemoryBlock[] blocks = currentProgram.getMemory().getBlocks();
		int blockCount = (blocks != null) ? blocks.length : 0;
		int functionCount = currentProgram.getFunctionManager().getFunctionCount();

		int stringCount = 0;
		DataIterator dataIt = currentProgram.getListing().getDefinedData(true);
		while (dataIt.hasNext()) {
			if (monitor.isCancelled()) {
				break;
			}
			if (dataIt.next().hasStringValue()) {
				stringCount++;
			}
		}

		int externalCount = 0;
		SymbolIterator extIt = currentProgram.getSymbolTable().getExternalSymbols();
		while (extIt.hasNext()) {
			if (monitor.isCancelled()) {
				break;
			}
			extIt.next();
			externalCount++;
		}

		File outFile = new File(resolveOutDir(), "triage.md");
		try (BufferedWriter w = new BufferedWriter(new FileWriter(outFile, StandardCharsets.UTF_8))) {
			w.write("# Triage Report\n\n");
			w.write("> Generated by the fork headless toolkit (read-only). Advisory summary.\n\n");
			w.write("| Field | Value |\n");
			w.write("| --- | --- |\n");
			w.write(row("Program name", name));
			w.write(row("Language", languageId));
			w.write(row("Compiler spec", compilerSpec));
			w.write(row("Image base", imageBase));
			w.write(row("Memory blocks", Integer.toString(blockCount)));
			w.write(row("Functions", Integer.toString(functionCount)));
			w.write(row("Defined strings", Integer.toString(stringCount)));
			w.write(row("External/import symbols", Integer.toString(externalCount)));
			w.write(row("Generated (UTC)", Instant.now().toString()));
			w.write("\nSee `functions.csv`, `strings.csv`, and `imports.csv` for details.\n");
		}
		println("ForkTriageReport: wrote " + outFile.getAbsolutePath());
	}

	private File resolveOutDir() {
		String[] args = getScriptArgs();
		File dir = (args != null && args.length > 0 && args[0] != null && !args[0].isEmpty())
				? new File(args[0]) : new File(".");
		dir.mkdirs();
		return dir;
	}

	// Render a Markdown table row, escaping pipe characters in the value.
	private static String row(String field, String value) {
		String v = (value != null) ? value.replace("|", "\\|") : "";
		return "| " + field + " | " + v + " |\n";
	}
}
